# Generated by Django 5.2.8 on 2025-11-18 18:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REGISTER', 'register'), ('LOGIN', 'login'), ('FORGOT_PASSWORD', 'forgot_password')], max_length=30)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('failed_attempt_frame_start', models.DateTimeField(blank=True, null=True)),
                ('generated_count', models.PositiveSmallIntegerField(default=0)),
                ('generate_frame_start', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'email'), name='unique_type_email')],
            },
        ),
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REGISTER', 'register'), ('LOGIN', 'login'), ('FORGOT_PASSWORD', 'forgot_password')], max_length=30)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('failed_attempt_frame_start', models.DateTimeField(blank=True, null=True)),
                ('generated_count', models.PositiveSmallIntegerField(default=0)),
                ('generate_frame_start', models.DateTimeField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'phone'), name='unique_type_phone')],
            },
        ),
    ]
