# Generated by Django 5.2.8 on 2025-11-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordEmailOtp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.emailotp',),
        ),
        migrations.CreateModel(
            name='LoginEmailOtp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.emailotp',),
        ),
        migrations.CreateModel(
            name='RegisterEmailOtp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.emailotp',),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='type',
            field=models.CharField(choices=[('REGISTER', 'register'), ('LOGIN', 'login'), ('FORGOT_PASSWORD', 'forgot_password')], default='REGISTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='type',
            field=models.CharField(choices=[('REGISTER', 'register'), ('LOGIN', 'login'), ('FORGOT_PASSWORD', 'forgot_password')], default='REGISTER', max_length=30),
        ),
    ]
