# Generated by Django 5.2.8 on 2025-11-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_forgotpasswordemailotp_loginemailotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordPhoneOtp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.phoneotp',),
        ),
        migrations.CreateModel(
            name='LoginPhoneOtp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.phoneotp',),
        ),
        migrations.CreateModel(
            name='RegisterPhoneOtp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.phoneotp',),
        ),
    ]
